### ISSUE TITLE
Running `npm install babel-preset-es-2015 --save-dev` returns a 404 error

### ISSUE THREAD

**Issue by leni1** [ccoenraets/es6-tutorial#18]
In Step 2: Set Up Babel, part 4 'Type the following command to install the ECMAScript 2015 preset', running `npm install babel-preset-es-2015 --save-dev` returns a 404 error. 

Full log: 
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'babel-preset-es-2015',
1 verbose cli   '--save-dev' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session dfa4b96f0b1a06e9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/babel-preset-es-2015 4494ms
8 silly fetchPackageMetaData error for babel-preset-es-2015@latest 404 Not Found: babel-preset-es-2015@latest
9 verbose stack Error: 404 Not Found: babel-preset-es-2015@latest
9 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:756:18)
9 verbose stack     at tryOnImmediate (timers.js:717:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
10 verbose cwd /home/user/es6-tutorial
11 verbose Linux 4.14.14-1-MANJARO
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "babel-preset-es-2015" "--save-dev"
13 verbose node v9.4.0
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: babel-preset-es-2015@latest
17 verbose exit [ 1, true ]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'babel-preset-es-2015',
1 verbose cli   '--save-dev' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session dfa4b96f0b1a06e9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/babel-preset-es-2015 4494ms
8 silly fetchPackageMetaData error for babel-preset-es-2015@latest 404 Not Found: babel-preset-es-2015@latest
9 verbose stack Error: 404 Not Found: babel-preset-es-2015@latest
9 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:756:18)
9 verbose stack     at tryOnImmediate (timers.js:717:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
10 verbose cwd /home/user/es6-tutorial
11 verbose Linux 4.14.14-1-MANJARO
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "babel-preset-es-2015" "--save-dev"
13 verbose node v9.4.0
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: babel-preset-es-2015@latest
17 verbose exit [ 1, true ]
```

I read in the Google search that I did using the error `fetchPackageMetaData error for babel-preset-es2015@latest 404 Not Found: babel-preset-es-2015@latest` that the present equivalent of `babel-preset-es-2015` is `babel-preset-env`, which was initially preceded by `babel-preset-latest` and is recommended when you run `npm install babel-preset-latest --save-dev`. 

So I've installed `babel-preset-env` as follows:
`npm install babel-preset-env --save-dev`

As a result, adding the code below to `package.json` means that running `npm run babel` returns an error as shown in the log further down. If possible it would be great to get some assistance as to how to adapt the code below to work with `babel-preset-env`.
```"scripts": {
    "babel": "babel --presets es2015 js/main.js -o build/main.bundle.js",
    "start": "http-server"
},
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'babel' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prebabel', 'babel', 'postbabel' ]
5 info lifecycle es6-tutorial@1.0.0~prebabel: es6-tutorial@1.0.0
6 info lifecycle es6-tutorial@1.0.0~babel: es6-tutorial@1.0.0
7 verbose lifecycle es6-tutorial@1.0.0~babel: unsafe-perm in lifecycle true
8 verbose lifecycle es6-tutorial@1.0.0~babel: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/es6-tutorial/node_modules/.bin:/home/user/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/adobe-air-sdk/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle es6-tutorial@1.0.0~babel: CWD: /home/user/es6-tutorial
10 silly lifecycle es6-tutorial@1.0.0~babel: Args: [ '-c',
10 silly lifecycle   'babel --presets es2015 js/main.js -o build/main.bundle.js' ]
11 silly lifecycle es6-tutorial@1.0.0~babel: Returned: code: 1  signal: null
12 info lifecycle es6-tutorial@1.0.0~babel: Failed to exec babel script
13 verbose stack Error: es6-tutorial@1.0.0 babel: `babel --presets es2015 js/main.js -o build/main.bundle.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid es6-tutorial@1.0.0
15 verbose cwd /home/user/es6-tutorial
16 verbose Linux 4.14.14-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "babel"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error es6-tutorial@1.0.0 babel: `babel --presets es2015 js/main.js -o build/main.bundle.js`
22 error Exit status 1
23 error Failed at the es6-tutorial@1.0.0 babel script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by UtkarshGupta-CS** [comment]
@leni1 it's [babel-preset-es2015](https://www.npmjs.com/package/babel-preset-es2015) not `babel-preset-es-2015`
Run, `npm install --save-dev babel-preset-es2015`

**Comment by leni1** [comment]
@UtkarshGupta-CS Thanks for that. However the log during install says:

```npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ babel-preset-es2015@6.24.1
added 1 package in 11.524s
```
Edit: I guess the tutorial may have to be rewritten to use `babel-preset-env` in future. As of now @UtkarshGupta-CS's answer solves my issue.
